version: '3'

services:
  redis:
    container_name: student_explorer_redis
    image: 'redis:3.2'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    entrypoint: redis-server --appendonly yes
    restart: on-failure
  mysql:
    image: mysql:5.7.22
    restart: on-failure
    environment:
      - MYSQL_HOST=${DJANGO_DB_HOST}
      - MYSQL_DATABASE=${DJANGO_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DJANGO_DB_USER}
      - MYSQL_PASSWORD=${DJANGO_DB_PASSWORD}
      - MYSQL_PORT=${DJANGO_DB_PORT}
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "2034:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    container_name: student_explorer_mysql
  web:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - LOCALHOST_DEV=1
            - ORACLE_CLIENT_VERSION=18.3
    command: bash -c "./start-localhost.sh"
    ports:
      - "2082:8000"
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      - LOCALHOST_DEV=1
    container_name: student_explorer
